### ISSUE TITLE
Gross output vs. value added

### ISSUE THREAD

**Issue by matthiasfru** [GabrieleRovigatti/prodest#10]
Hi Gabriele,

thank you for the awesome package! 
I was wondering if it is possible to estimate a gross output production function with this package? I'm not sure since in the documentation it says input Y should be value added but in the details simply log output, and I believe in the STATA version the default is gross output.

So for example, if I have information on log sales/revenue, COGS and capital (identification issues aside),
```R
prodestACF(Y = sales, fX = COGS , sX = capital, pX = COGS, ...)
```
would just be flat out wrong, no?
Thank you,
Best Matthias

**Comment by GabrieleRovigatti** [comment]
Dear Matthias,

thanks for the message, I am glad that you found _prodest_ useful. 

Unfortunately, the R version of the package is way less developed than its Stata counterpart, and does not allow for a gross output model estimation - even though, as you correctly pointed out, it is the default in the other version. 

As you might guess, given the VA functional form, the model you are trying to estimate would not work. I hope that I will have time to implement the GO models soon but, for the time being, you might rely on the Stata version - identifications issues aside, as I am not going to enter into the debate over the DLEU model. 

I hope to have clarified, 

Gabriele

**Comment by matthiasfru** [comment]
Thank you very much for the quick response and clarification!
