### ISSUE TITLE
Omega estimates from WRDG_GMM

### ISSUE THREAD

**Issue by awatt43** [GabrieleRovigatti/prodest#19]
Hi there

I cannot obtain the omega estimates from the example given in the package when using the Wooldridge GMM estimator.

I get the following error:
![image](https://user-images.githubusercontent.com/77967582/106131501-aa79ec00-615a-11eb-9f28-cbf71be57b4e.png)

I am assuming that this is because we are using lags as instruments in the GMM process so we lose observations therefore the VA (Y) is 1x1944 whilst the state & free vars are 1x2544. I can manually compute the omega but I wanted to check whether this was user error on my part? 

Thanks,
Abigail

**Comment by GabrieleRovigatti** [comment]
Hi Abigail,

you are exactly right - the use of lagged instruments is the reason for the different number of dimensions between Y and the estimation variables. 

I will commit the bug fixes as soon as possible, thanks for pointing this out!

Gabriele
