### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sebastianbarfort** [GabrieleRovigatti/prodest#2]
Hi, 

I'm currently reviewing your package for JOSS. Can you please add a license with the contents of an OSI approved software license?

Cheers, 
Sebastian

**Comment by GabrieleRovigatti** [comment]
Hi Sebastian,

thanks for your effort in reviewing the code. I have a file LICENSE in the main prodest directory - covering both the Stata and the R routines - which should be an approved OSI one (in particular, is a GPL3). Would you require a more specific / different one?

Thanks,

Gabriele

**Comment by sebastianbarfort** [comment]
Hi Gabriele, 

Okay great, had not seen the license in the main directory. Closing. 

Thanks! 

Seb
