### ISSUE TITLE
FSres does not work

### ISSUE THREAD

**Issue by yang2021aa** [GabrieleRovigatti/prodest#24]
FSres does work for prodestACF, prodestLP and prodestOP,  
but **does not work** for prodestROB, prodestWRDG, and prodestWRDG_GMM
please help to update it, thanks a lot.

**Comment by GabrieleRovigatti** [comment]
Hi,

FSres does not work with one-step estimations like ROB, WRDG, and WRDG_GMM because there is no First Stage to get the RESiduals of (nor you'll ever need them to retrieve omega in those cases). 

Best,

**Comment by yang2021aa** [comment]
thanks a lot
