### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by sebastianbarfort** [GabrieleRovigatti/prodest#4]
Hi again, 

Could you include an example of how to use the package - for example at the end of the README.md file? I know that the functions are documented in the CRAN package documentation, but a brief example would definitely increase usability. 

Cheers, 
Sebastian

**Comment by GabrieleRovigatti** [comment]
Dear Sebastian,

I added a section 'Example' at the end of the README.md file with one example - taken from the 'prodestLP.R' documentation - which documents the basic usage and the results reporting.

Best,

Gabriele
