### ISSUE TITLE
Industry fixed effects

### ISSUE THREAD

**Issue by jayhjim88** [GabrieleRovigatti/prodest#8]
Dear Gabriele,
Thanks for the useful package. I would ask you how shall one use industry fixed effect in your functions.
For instance, say that Chilean data further contained a few industries of data, for example, car/textile etc.
Is there any way that your existing functions could incorporate industry fixed effect, probably encoded as a factor variable? Will you provide an example if so?
Best regards,

**Comment by GabrieleRovigatti** [comment]
Dear jayhjim, 

at the moment, the control() option in prodest - Stata version - might be used to add industry fixed effects. However, a similar feature has still to be implemented in the R version. 

Best,

Gabriele
