### ISSUE TITLE
Sampling weights option

### ISSUE THREAD

**Issue by luisvalenzuelar** [GabrieleRovigatti/prodest#9]
Hi Gabriele,

Superb package!

For us who work with survey data however, sampling weights oftentimes need to be taken into account. Is it possible to implement the methods in the package with weights? So far I see no option for this.

Cheers.

**Comment by GabrieleRovigatti** [comment]
Hi @raspatan ,

thanks for the message, and I am glad you found _prodest_ useful. 

Unfortunately, it is not possible to use sampling weights at the moment: I will take a note and try to implement this feature soon! 

Best,
